# Generated by Django 5.1.3 on 2024-11-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0002_tipoinmueble'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoInmueble',
        ),
    ]
