# Generated by Django 5.1.3 on 2024-11-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0009_inmueble_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen_inmueble',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles'),
        ),
        migrations.AlterField(
            model_name='region',
            name='imagen_region',
            field=models.ImageField(default='arica.jpg', upload_to='regiones'),
        ),
    ]
